name: crimes
description: A new Flutter application.
version: 3.0.2+3


environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_mobx: ^2.2.0+1
  freezed: ^2.4.5
# firebase_core: ^2.24.2
# firebase_analytics: ^10.7.4
# firebase_crashlytics: ^3.4.8
# firebase_messaging: ^14.7.8
  firebase_core: ^2.27.0
  firebase_crashlytics: ^3.4.18
  firebase_messaging: ^14.7.19
  google_mlkit_text_recognition: ^0.11.0

  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  #flutter_sodium: ^0.2.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  gson: ^0.1.6-dev

  local_auth: ^2.1.7
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  intl: ^0.18.1

  cupertino_icons: ^1.0.6
#  image: ^4.1.2
  flutter_screenutil: ^5.9.0
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  image_picker: ^1.0.4
  camera: ^0.10.5+6
  font_awesome_flutter: ^10.6.0
  pin_input_text_field: ^4.5.1
  device_info_plus: ^9.1.1
  pdf: ^3.10.7
  excel: ^4.0.0
  google_fonts: ^6.1.0
  dotted_decoration: ^2.0.0
  url_launcher: ^6.2.2
  flutter_exif_rotation: ^0.5.1
  flutter_image_compress: ^2.1.0
  webview_flutter: ^4.4.2
  bot_toast: ^4.1.3
  geolocator: ^10.1.0
  package_info_plus: ^5.0.1
  tutorial_coach_mark: ^1.2.11
  after_layout: ^1.2.0
  image_cropper: ^5.0.1

  flutter_spinkit: ^5.2.0
  bordered_text: ^2.0.0
  carousel_slider: ^4.2.1
  clipboard: ^0.1.3
  async: ^2.11.0
  connectivity_plus: ^5.0.2
  logger: ^2.0.2+1
  flutter_app_badger: ^1.5.0
  flutter_local_notifications: ^16.2.0
  event_bus: ^2.0.0
  store_redirect: ^2.0.1
  map_launcher: ^3.1.0
  app_settings: ^5.1.1
  encrypt: ^5.0.3
  scan: ^1.6.0
  uni_links: ^0.5.1
  sodium_libs: ^2.2.0+6
  app_tracking_transparency: ^2.0.4
  syncfusion_flutter_pdfviewer: ^23.2.7
  google_mlkit_barcode_scanning: ^0.10.0
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.5
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
  fonts:
    - family: Sukhumvit
      fonts:
      - asset: assets/fonts/SukhumvitSet-Bold.ttf
      - asset: assets/fonts/SukhumvitSet-Light.ttf
      - asset: assets/fonts/SukhumvitSet-Medium.ttf
      - asset: assets/fonts/SukhumvitSet-SemiBold.ttf
      - asset: assets/fonts/SukhumvitSet-Text.ttf
      - asset: assets/fonts/SukhumvitSet-Thin.ttf
#        weight: 700
